ProFit Event App/objects/Attendee__c.object
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFit Event App/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <description>Event Ending Date &amp; Time</description>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date_Time__c</fullName>
        <description>Starting Date &amp; Time of Event</description>
        <label>Event Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the event will be streamed online</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Maximum Available Seats for the Event</description>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Event List</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Event Attendee</description>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_List__c</fullName>
        <description>Event to Attend</description>
        <label>Event List</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit Event App/objects/Event_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Event_List__c</fullName>
        <description>Event to Attend</description>
        <label>Event List</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Event Speaker</description>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit Event App/objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFit Event App/classes/EventDetailsController_Test.cls
@isTest
public with sharing class EventDetailsController_Test {
    static Id createTestEvent(){
        Event__c evt = new Event__c();
        evt.Name__c = 'Test Event 5';
        evt.Event_Start_Date_Time__c = datetime.newInstance(2021, 6, 26, 19, 30, 0);
        evt.Event_End_Date_Time__c = datetime.newInstance(2021, 6, 28, 20, 30, 0);
        evt.Max_Seats__c = 5;
        evt.Live__c = true;
        insert evt;
        return evt.Id;
    }
    static Id createTestSpeaker(){
        Speaker__c spk = new Speaker__c();
        spk.Name = 'Test Speaker 5';
        insert spk;
        return spk.Id;
    }
    static Id createTestAttendee(){
        Attendee__c att = new Attendee__c();
        att.Name = 'Test Attendee 5';
        insert att;
        return att.Id;
    }
    @IsTest
    static void testSpeaker(){
        
        Test.startTest();
        String recId;
        Event_Speaker__c eSpeaker = new Event_Speaker__c();
        eSpeaker.Event_List__c = createTestEvent();
        eSpeaker.Speaker__c = createTestSpeaker();
        eSpeaker.Name = 'Test Name 5';
        Event_Speaker__c name;
        String str = '';
        insert eSpeaker;
        List<Event_Speaker__c> retrievedSpeaker = EventDetailsController.getSpeakers(eSpeaker.Event_List__c);
        name = retrievedSpeaker.get(0);
        Test.stopTest();
        System.assertEquals('Test Name 5',name.Name);
    }
    @IsTest
    static void testLocation(){
        Test.startTest();
        String recId = createTestEvent();
        Event__c evts = EventDetailsController.getLocationDetails(recId);
        Test.stopTest();
        System.assertEquals('Test Event 5',evts.Name__c);
    }
    @isTest
    static void testAttendee(){
        Test.startTest();
        Event_Attendee__c eAttendee = new Event_Attendee__c();
        eAttendee.Attendee__c = createTestAttendee();
        eAttendee.Event_List__c = createTestEvent();
        eAttendee.Name = 'Test Attendee 5';
        insert eAttendee;
        Event_Attendee__c name;
        List<Event_Attendee__c> retrievedAttendee = EventDetailsController.getAttendees(eAttendee.Event_List__c);
        name = retrievedAttendee.get(0);
        
        Test.stopTest();
        System.assertEquals('Test Attendee 5', name.Name);
    }
}