ProFit Event App/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Location_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Attendee&apos;s Address</description>
        <label>Location List</label>
        <referenceTo>Location_List__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFit Event App/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <description>Event Ending Date &amp; Time</description>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date_Time__c</fullName>
        <description>Starting Date &amp; Time of Event</description>
        <label>Event Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event Location</description>
        <label>Location List</label>
        <referenceTo>Location_List__c</referenceTo>
        <relationshipLabel>Event List</relationshipLabel>
        <relationshipName>Event_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Event List</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Event Attendee</description>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_List__c</fullName>
        <description>Event to Attend</description>
        <label>Event List</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit Event App/objects/Location_List__c.object
<CustomObject>
    <label>Location List</label>
    <nameField>
        <label>Location List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/classes/AttendeeEventsController.cls
public with sharing class AttendeeEventsController {
    @AuraEnabled(cacheable=true)
    public static List<Event_Attendee__c> futureEvents(String attendeeId) {
        List<Event_Attendee__c> eventLists = 
        [SELECT 
        Id, 
        Name, 
        Event_List__c, 
        Event_List__r.Name__c, 
        Event_List__r.Location_List__r.Name,
        Event_List__r.Event_Start_Date_Time__c, 
        Event_List__r.Event_End_Date_Time__c 
        FROM Event_Attendee__c 
        WHERE Attendee__c = :attendeeId 
        AND Event_List__r.Event_Start_Date_Time__c >= today ];
        return eventLists;

    }

    @AuraEnabled(cacheable=true)
    public static List<Event_Attendee__c> pastEvents(String attendeeId) {
        List<Event_Attendee__c> eventLists = 
        [SELECT 
        Id, 
        Name, 
        Event_List__c, 
        Event_List__r.Name__c, 
        Event_List__r.Location_List__r.Name,
        Event_List__r.Event_Start_Date_Time__c, 
        Event_List__r.Event_End_Date_Time__c 
        FROM Event_Attendee__c 
        WHERE Attendee__c = :attendeeId 
        AND Event_List__r.Event_Start_Date_Time__c < today ];
        return eventLists;
    }
}