ProFit Event App/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Log_Date_Time__c</fullName>
        <description>Log Date and Time of Occurance</description>
        <label>Log Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Log_Details__c</fullName>
        <description>Detailed Information of the Error Log</description>
        <label>Log Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>Cause of the Error</description>
        <label>Process Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProFit Event App/classes/ErrorLogGenerator_Test.cls
@isTest
public with sharing class ErrorLogGenerator_Test {
    @IsTest
    static void testError(){
        
        Test.startTest();
        DateTime edatetime = datetime.newInstance(2021, 6, 21, 19, 30, 0);
        String edetails = 'Error Test';
        String ename = 'Test Error Name';
        ErrorLogGenerator.createErrorLog(ename,edetails, edatetime);

        Test.stopTest();
        Error_Log__c eLog = [Select Id, Log_Date_Time__c, Log_Details__c, Process_Name__c from Error_Log__c];
        System.assertEquals('Test Error Name', eLog.Process_Name__c);
    }
}