ProFit Event App/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <description>Event Ending Date &amp; Time</description>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <description>Current Status of the Event</description>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the event will be streamed online</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <label>Event List</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/classes/UpdateEventStatusBatch.cls
public class UpdateEventStatusBatch implements Database.Batchable<sObject> {
	
    public Database.QueryLocator start(Database.BatchableContext batchContext){
        String Query = 'Select Id, Name From Event__c Where Live__c = false AND Event_Status__c != \'Completed\' AND Event_End_Date_Time__c < LAST_N_MONTHS:4';
        return Database.getQueryLocator(Query);
        
    }

    public void execute(Database.BatchableContext batchContext, List<Event__c> eventList ){
        List<Event__c> dEvent = new List<Event__c>();
        for(Event__c evt: eventList){
            evt.Event_Status__c = 'Deleted';
            dEvent.add(evt);
        }
        update dEvent;
    }
    
    public void finish(Database.BatchableContext batchContext){
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        
        email.setSubject('Batch Processing');
        List<String> toAddress = new List<String>();
        toAddress.add(Contact.Email__c);
        email.setToAddresses( toAddress );
        email.setSenderDisplayName('Christian Castor');
        
        email.setHtmlBody('The Event was deleted');
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage> {email};
        Messaging.sendEmail(emails);
    }
}