ProFit Event App/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <description>Event Ending Date &amp; Time</description>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date_Time__c</fullName>
        <description>Starting Date &amp; Time of Event</description>
        <label>Event Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <description>Current Status of the Event</description>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the event will be streamed online</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Maximum Available Seats for the Event</description>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Event List</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/classes/UpdateEventStatusBatch_Test.cls
@isTest
public class UpdateEventStatusBatch_Test {
    public static testMethod void testUpdateStatusBatch() {

        List<Event__c> eList = new List<Event__c>();
        for(Integer i=0; i<=100; i++){
            Event__c evnt = new Event__c(
                Name__c = 'Test #' +1,
                Event_Status__c = 'Created',
                Event_Start_Date_Time__c = datetime.newInstance(2020, 7, 16, 08, 30, 0),
                Event_End_Date_Time__c = datetime.newInstance(2020, 7, 19, 20, 0, 0),
                Max_Seats__c = 10,
                Live__c = false
                );
                eList.add(evnt);
        }
        insert eList;
        
        try{
            Test.startTest();

            Id batchId = Database.executeBatch(new UpdateEventStatusBatch(), 150);

            Test.stopTest();
        }
        catch (Exception ex){

        }
        System.AssertEquals(database.countquery('SELECT COUNT()' + ' FROM Event__c Where Event_Status__c != \'Completed\''), 101);

    }
}