ProFit Event App/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <description>Event Ending Date &amp; Time</description>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date_Time__c</fullName>
        <description>Starting Date &amp; Time of Event</description>
        <label>Event Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <description>Current Status of the Event</description>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Event Attendance Type</description>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the event will be streamed online</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Event List</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/classes/EventDetailsRestService_Test.cls
@istest
public with sharing class EventDetailsRestService_Test {
    static Id createEventTestRecord(){
        Event__c evt = new Event__c();
        evt.Name__c = 'Test Record REST Service';
        evt.Event_Start_Date_Time__c = datetime.newInstance(2021, 6, 26, 11, 00, 0);
        evt.Event_End_Date_Time__c = datetime.newInstance(2021, 6, 27, 12, 00, 0);
        evt.Event_Type__c ='Virtual';
        evt.Live__c = true;
        evt.Event_Status__c = 'Created';
        insert evt;
        return evt.Id;
    }
    @IsTest
    static void doGetTest(){
        Test.startTest();
            Id EventId =  createEventTestRecord();
            RestRequest req = new RestRequest();
            req.requestURI = 'abctechnologies2--capstonesb.my.salesforce.com/services/apexrest/api/Event__c/'+EventId;
            req.httpMethod = 'GET';
            RestContext.request = req;
            Event__c evt = EventDetailsRestService.doGetEvt();
            System.assertEquals(EventId, evt.Id);
        Test.stopTest();
    }
}