ProFit Event App/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <description>Event Ending Date &amp; Time</description>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date_Time__c</fullName>
        <description>Starting Date &amp; Time of Event</description>
        <label>Event Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the event will be streamed online</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Event List</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/objects/Event_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Event_List__c</fullName>
        <description>Event to Attend</description>
        <label>Event List</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Event Speaker</description>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit Event App/objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFit Event App/classes/DuplicateEventSpeakerTrigger_Test.cls
@isTest
private class DuplicateEventSpeakerTrigger_Test {
    
    static Id createTestRecordID(){
      Event__c evt = new Event__c();
      evt.Name__c = 'Test Event';
      evt.Live__c = true;
      evt.Event_Start_Date_Time__c = datetime.newInstance(2021, 6, 26, 19, 30, 0);
      evt.Event_End_Date_Time__c = datetime.newInstance(2021, 6, 28, 20, 30, 0);
      insert evt;
      return evt.Id;
    }
    static Id createTestSpeaker(){
      Speaker__c spk = new Speaker__c();
      spk.Name = 'Test Speaker';
      insert spk;
      return spk.Id;
  }

    @IsTest
    static void checkEventSpeaker(){
      Test.startTest();
      Event_Speaker__c eS = new Event_Speaker__c();
      eS.Name = 'Test Event-Speaker';
      eS.Event_List__c = createTestRecordID();
      eS.Speaker__c = createTestSpeaker();
        
      insert eS;
      Test.stopTest();
      Event_Speaker__c retrievedES = [Select Name from Event_Speaker__c where Name =: eS.Name];
      System.assertEquals('Test Event-Speaker',retrievedES.Name);
          
      }
}