ProFit Event App/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <description>Event Ending Date &amp; Time</description>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date_Time__c</fullName>
        <description>Starting Date &amp; Time of Event</description>
        <label>Event Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event List</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/objects/Event_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Event_List__c</fullName>
        <description>Event to Attend</description>
        <label>Event List</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Event Speaker</description>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit Event App/objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFit Event App/classes/DuplicateEventSpeakerTrigger.cls
public with sharing class DuplicateEventSpeakerTrigger {
    public static void eventSpeakerDuplicate(List<Event_Speaker__c> newSpeaker){
        try{

            Set<Id> eventId = new Set<Id>();
            Set<Id> speakerId = new Set<Id>();

            for(Event_Speaker__c eSpeaker : newSpeaker){
                eventId.add(eSpeaker.Event_List__c);
                speakerId.add(eSpeaker.Speaker__c);
            }

            Map<Id, Event__c> startEvent = new Map<Id, DateTime>();
            Map<Id, DateTime> endEvent = new Map<Id, DateTime>();

            List<Event__c> eventList = [
                SELECT Id, Name, Event_Start_Date_Time__c, Event_End_Date_Time__c 
                FROM Event__c 
                WHERE Id IN: eventId];

            for(Event__c evt : eventList){
                startEvent.put(evt.Id, evt.Event__r.Event_Start_Date_Time__c);
                endEvent.put(evt.Id, evt.Event_End_Date_Time__c);
            }

            List<Event_Speaker__c> speakerList = [
                SELECT Id, Event_List__c, Speaker__c, Event_List__r.Event_Start_Date_Time__c, Event_List__r.Event_End_Date_Time__c
                FROM Event_Speaker__c 
                WHERE Speaker__c IN: speakerID];

            for(Event_Speaker__c eSpeaker : newSpeaker) {
                DateTime startTime = startEvent.get(eSpeaker.Event_List__c);
                DateTime endTime = endEvent.get(eSpeaker.Event_List__c);

                for(Event_Speaker__c eS : speakerList)
                {
                    if((eS.Event_List__r.Event_Start_Date_Time__c < endTime && eS.Event_List__r.Event_End_Date_Time__c > endTime)
                     ||(eS.Event_List__r.Event_Start_Date_Time__c < startTime && eS.Event_List__r.Event_End_Date_Time__c > startTime)
                     ||(eS.Event_List__r.Event_Start_Date_Time__c >= startTime && eS.Event_List__r.Event_End_Date_Time__c <= endTime))
                        {
                            eSpeaker.Speaker__c.addError('The Speaker is already registered to another event at the time.');
                        }
                }
            }
            // for(Event_Speaker__c eSpeaker : newSpeaker){
                
            //     Event__c eDate = [Select Event_Start_Date_Time__c, Event_End_Date_Time__c from Event__c where Id =: eSpeaker.Event_List__c];
            //     System.debug(eDate.Event_Start_Date_Time__c);
            //     System.debug(eDate.Event_End_Date_Time__c);

            //     List<Event_Speaker__c> eventSpeaker = [SELECT Id, Event_List__c, Speaker__c FROM Event_Speaker__c 
            //     WHERE (Speaker__c =: eSpeaker.Speaker__c)
            //     AND ((Event_List__r.Event_Start_Date_Time__c <: eDate.Event_End_Date_Time__c AND Event_List__r.Event_End_Date_Time__c >: eDate.Event_End_Date_Time__c)
            //     OR (Event_List__r.Event_Start_Date_Time__c <: eDate.Event_Start_Date_Time__c AND Event_List__r.Event_End_Date_Time__c >: eDate.Event_Start_Date_Time__c))];
                
            //     if(eventSpeaker.size()>0){
            //         eSpeaker.Speaker__c.addError('This speaker is registered to another event already');
            //     }
            // }
        }catch (Exception ex){
            System.debug('Exception: '+ex.getMessage());
        }
    }
}