ProFit Event App/objects/Location_List__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>City Name</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_code__c</fullName>
        <description>Postal Code</description>
        <label>Postal code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State Name</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street Name</description>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verified_Location__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Verification for Location</description>
        <label>Verified Location</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Verified_Postal_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Verified Postal Code</label>
        <type>Checkbox</type>
    </fields>
    <label>Location List</label>
    <nameField>
        <label>Location List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location List</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit Event App/classes/ZipVerifier_Test.cls
@isTest
public with sharing class ZipVerifier_Test {
    public static testMethod void testZip(){

        Location_List__c loc = new Location_List__c(
            Name = '3301 South Greenfield Rd',
            Street__c = '3301 South Greenfield Rd',
            City__c = 'Gilbert',
            State__c = 'AZ',
            Postal_Code__c = '85297',
            Country__c = 'United States'
        );
        insert loc;



        try{
            Test.setMock(HttpCalloutMock.class, new ZipMock());
            Test.startTest();

            ZipVerifier.zipCodeCallOut(''+loc.Id+'');
            
            Test.stopTest();
        }catch(Exception ex){

        }
        Location_List__c retrievedZipVerified = [Select Verified_Postal_Code__c from Location_List__c where Id =: loc.Id];
        System.assertEquals(true, retrievedZipVerified.Verified_Postal_Code__c);

    }
    public static testMethod void testLoc(){
        Location_List__c loc = new Location_List__c(
            Name = '3301 South Greenfield Rd',
            Street__c = '3301 South Greenfield Rd',
            City__c = 'Gilbert',
            State__c = 'AZ',
            Postal_Code__c = '85297',
            Country__c = 'United States'
        );
        insert loc;

        try{
            Test.setMock(HttpCalloutMock.class, new LocationMock());
            Test.startTest();

            ZipVerifier.locationCall(''+loc.Id+'');
            
            Test.stopTest();
        }catch(Exception ex){

        }
        Location_List__c retrievedLocVerified = [Select Verified_Location__c from Location_List__c where Id =: loc.Id];
        System.assertEquals(true,retrievedLocVerified.Verified_Location__c);
    }

}